main() {
  sum = 0;
  for (i = 1; i <= 1000; i++) {
	sum += count(i);
  }
  __outn(sum);
}

count(x) {
  if (x == 0) {
    return 4;
  }
  if (x == 1) {
    return 3;
  }
  if (x == 2) {
    return 3;
  }
  if (x == 3) {
    return 5;
  }
  if (x == 4) {
    return 4;
  }
  if (x == 5) {
    return 4;
  }
  if (x == 6) {
    return 3;
  }
  if (x == 7) {
    return 5;
  }
  if (x == 8) {
    return 5;
  }
  if (x == 9) {
    return 4;
  }
  if (x == 10) {
    return 3;
  }
  if (x == 11) {
    return 6;
  }
  if (x == 12) {
    return 6;
  }
  if (x == 13) {
    return 8;
  }
  if (x == 14) {
    return 8;
  }
  if (x == 15) {
    return 7;
  }
  if (x == 16) {
    return 7;
  }
  if (x == 17) {
    return 9;
  }
  if (x == 18) {
    return 8;
  }
  if (x == 19) {
    return 8;
  }
  if (x == 20) {
    return 6;
  }
  if (x == 21) {
    return 9;
  }
  if (x == 22) {
    return 9;
  }
  if (x == 23) {
    return 11;
  }
  if (x == 24) {
    return 10;
  }
  if (x == 25) {
    return 10;
  }
  if (x == 26) {
    return 9;
  }
  if (x == 27) {
    return 11;
  }
  if (x == 28) {
    return 11;
  }
  if (x == 29) {
    return 10;
  }
  if (x == 30) {
    return 6;
  }
  if (x == 31) {
    return 9;
  }
  if (x == 32) {
    return 9;
  }
  if (x == 33) {
    return 11;
  }
  if (x == 34) {
    return 10;
  }
  if (x == 35) {
    return 10;
  }
  if (x == 36) {
    return 9;
  }
  if (x == 37) {
    return 11;
  }
  if (x == 38) {
    return 11;
  }
  if (x == 39) {
    return 10;
  }
  if (x == 40) {
    return 5;
  }
  if (x == 41) {
    return 8;
  }
  if (x == 42) {
    return 8;
  }
  if (x == 43) {
    return 10;
  }
  if (x == 44) {
    return 9;
  }
  if (x == 45) {
    return 9;
  }
  if (x == 46) {
    return 8;
  }
  if (x == 47) {
    return 10;
  }
  if (x == 48) {
    return 10;
  }
  if (x == 49) {
    return 9;
  }
  if (x == 50) {
    return 5;
  }
  if (x == 51) {
    return 8;
  }
  if (x == 52) {
    return 8;
  }
  if (x == 53) {
    return 10;
  }
  if (x == 54) {
    return 9;
  }
  if (x == 55) {
    return 9;
  }
  if (x == 56) {
    return 8;
  }
  if (x == 57) {
    return 10;
  }
  if (x == 58) {
    return 10;
  }
  if (x == 59) {
    return 9;
  }
  if (x == 60) {
    return 5;
  }
  if (x == 61) {
    return 8;
  }
  if (x == 62) {
    return 8;
  }
  if (x == 63) {
    return 10;
  }
  if (x == 64) {
    return 9;
  }
  if (x == 65) {
    return 9;
  }
  if (x == 66) {
    return 8;
  }
  if (x == 67) {
    return 10;
  }
  if (x == 68) {
    return 10;
  }
  if (x == 69) {
    return 9;
  }
  if (x == 70) {
    return 7;
  }
  if (x == 71) {
    return 10;
  }
  if (x == 72) {
    return 10;
  }
  if (x == 73) {
    return 12;
  }
  if (x == 74) {
    return 11;
  }
  if (x == 75) {
    return 11;
  }
  if (x == 76) {
    return 10;
  }
  if (x == 77) {
    return 12;
  }
  if (x == 78) {
    return 12;
  }
  if (x == 79) {
    return 11;
  }
  if (x == 80) {
    return 6;
  }
  if (x == 81) {
    return 9;
  }
  if (x == 82) {
    return 9;
  }
  if (x == 83) {
    return 11;
  }
  if (x == 84) {
    return 10;
  }
  if (x == 85) {
    return 10;
  }
  if (x == 86) {
    return 9;
  }
  if (x == 87) {
    return 11;
  }
  if (x == 88) {
    return 11;
  }
  if (x == 89) {
    return 10;
  }
  if (x == 90) {
    return 6;
  }
  if (x == 91) {
    return 9;
  }
  if (x == 92) {
    return 9;
  }
  if (x == 93) {
    return 11;
  }
  if (x == 94) {
    return 10;
  }
  if (x == 95) {
    return 10;
  }
  if (x == 96) {
    return 9;
  }
  if (x == 97) {
    return 11;
  }
  if (x == 98) {
    return 11;
  }
  if (x == 99) {
    return 10;
  }
  if (x == 1000) {
    return 11;
  }
  if (x % 100 == 0) {
    return count(x/100) + 7;
  }
  return count(x/100) + 10 + count(x%100);
}
